all:
  vars:
    control_plane_endpoint: 192.168.0.150
    load_balancer_ip_pool:
      - 192.168.0.200/29
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.0.150, mac: '10:bf:48:7a:ca:7a', disk: sda, network_interface: enp3s0}
    workers:
      hosts:
        metal3: {}
